=== olya7viit/XML_EPAM/src/main/resources/data/candies.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/candies"
        xmlns:tns="http://www.example.com/candies"
        elementFormDefault="qualified">
    <element name="candies">
        <complexType>
            <sequence>
                <element name="candy" type="tns:Candy"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="Candy">
        <sequence>
            <element name="name" type="string"/>
            <element name="energy" type="positiveInteger"/>
            <element name="ingredients">
                <complexType>
                    <sequence>
                        <element name="water" type="positiveInteger"/>
                        <element name="sugar" type="positiveInteger"/>
                        <element name="fructose" type="positiveInteger"/>
                    </sequence>
                </complexType>
            </element>
            <element name="value">
                <complexType>
                    <sequence>
                        <element name="proteins" type="double"/>
                        <element name="fats" type="double"/>
                        <element name="carbohydrates" type="double"/>
                    </sequence>
                </complexType>
            </element>
            <element name="production" type="string"/>
            <element name="date" type="date"/>
        </sequence>

        <attribute name="id" type="tns:id" use="required"/>

        <attribute name="type" default="шоколадная">
            <simpleType>
                <restriction base="string">
                    <enumeration value="желейная"></enumeration>
                    <enumeration value="шоколадная"></enumeration>
                    <enumeration value="карамель"></enumeration>
                    <enumeration value="ирис"></enumeration>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>

    <simpleType name="id">
        <restriction base="ID">
            <pattern value="ID\d+"/>
        </restriction>
    </simpleType>
</schema>

=== olya7viit/XML_EPAM/src/main/resources/data/candies.xml
<?xml version="1.0" encoding="UTF-8"?>
<candies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.example.com/candies"
         xsi:schemaLocation="http://www.example.com/candies candies.xsd">

    <candy id="ID1" type="желейная">
        <name>Бешеная пчёлка фрутти</name>
        <energy>322</energy>
        <ingredients>
            <water>20</water>
            <sugar>40</sugar>
            <fructose>30</fructose>
        </ingredients>
        <value>
            <proteins>0.3</proteins>
            <fats>0.6</fats>
            <carbohydrates>79.6</carbohydrates>
        </value>
        <production>Roshen</production>
        <date>2020-05-13</date>
    </candy>

    <candy id="ID2" type="шоколадная">
        <name>Сорванец</name>
        <energy>539</energy>
        <ingredients>
            <water>20</water>
            <sugar>40</sugar>
            <fructose>30</fructose>
        </ingredients>
        <value>
            <proteins>7.4</proteins>
            <fats>33.9</fats>
            <carbohydrates>51.8</carbohydrates>
        </value>
        <production>Коммунарка</production>
        <date>2020-04-13</date>
    </candy>

    <candy id="ID3" type="карамель">
        <name>Карамель Джус-микс «Roshen» с фруктово-ягодной начинкой</name>
        <energy>380</energy>
        <ingredients>
            <water>70</water>
            <sugar>40</sugar>
            <fructose>30</fructose>
        </ingredients>
        <value>
            <proteins>0.0</proteins>
            <fats>0.0</fats>
            <carbohydrates>94.4</carbohydrates>
        </value>
        <production>Roshen</production>
        <date>2020-05-25</date>
    </candy>
</candies>
